name: tasker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modular_ui: ^0.0.5
  flutter_modular: ^6.3.3
  gap: ^3.0.1
  google_fonts: 6.1.0
  dotted_border: ^2.1.0
  very_good_analysis: ^5.1.0
  equatable: ^2.0.5
  emoji_picker_flutter: ^2.1.1
  lucid_validation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
